# Dependencies
#markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Zach White
tagline:          'A programmer with experience at scale.'
description:      'A practical programmer with 2 decades of experience.<br><br>I will solve your business needs by building backend systems suited to your level of scale.'
url:              http://skullydazed.github.io/
baseurl:          /portfolio

author:
  name:           'Zach White'
  url:            https://githum.com/skullydazed

# Custom vars
version:          2.1.0
github:           
  repo:           https://github.com/skullydazed/portfolio
